from __future__ import annotations

from readright.intelligence.intervention_models import InterventionSpec


INTERVENTIONS: dict[str, InterventionSpec] = {
    "INT-GPC-EXPLICIT": InterventionSpec(
        intervention_id="INT-GPC-EXPLICIT",
        hypothesis_id="H-GPC",
        target_skill_id="EN-GPC",
        title="Explicit print-to-sound mapping routine",
        purpose="Strengthen reliable recognition of taught grapheme-phoneme correspondences.",
        group_size="1-4 learners",
        duration_minutes=8,
        sessions_per_week=4,
        delivery_principles=[
            "Teach a small set explicitly and cumulatively.",
            "Model once, then move quickly to learner production.",
            "Mix known and newly taught correspondences.",
            "Keep response opportunities frequent and brief.",
        ],
        steps=[
            "Review 3-5 previously taught graphemes.",
            "Introduce at most 1-2 target graphemes with their common sounds.",
            "Teacher models the sound once without adding a schwa.",
            "Learner produces the sound for shuffled graphemes.",
            "Learner identifies the grapheme when the teacher says the sound.",
            "Finish with a short mixed retrieval check using unseen order.",
        ],
        practice_constraints=[
            "Use only grapheme-sound correspondences selected for the learner's instruction sequence.",
            "Do not count prompted/modelled responses as independent success.",
            "Avoid introducing several confusable symbols in the same first teaching step.",
        ],
        do_not_do=[
            "Do not use letter-shape reversals as evidence of dyslexia.",
            "Do not infer mastery from one successful trial.",
        ],
        expected_immediate_signal="Higher independent accuracy on the explicitly taught correspondences.",
        expected_transfer_signal="Improved decoding on unfamiliar items containing the taught correspondences.",
        falsification_signal="Accurate grapheme-sound mapping improves but decoding remains weak on matched unfamiliar items.",
        evidence_basis=[
            "Explicit, systematic instruction in alphabetic knowledge and sound-symbol relationships is a core foundational-reading practice.",
            "ReadRight pilot implementation requires calibration before effectiveness claims.",
        ],
    ),
    "INT-BLEND-EXPLICIT": InterventionSpec(
        intervention_id="INT-BLEND-EXPLICIT",
        hypothesis_id="H-BLEND",
        target_skill_id="EN-PHON-BLEND-CVC",
        title="Explicit phoneme blending routine",
        purpose="Build the learner's ability to combine sequential phonemes into a spoken word.",
        group_size="1-4 learners",
        duration_minutes=8,
        sessions_per_week=4,
        delivery_principles=[
            "Begin orally before adding print when blending itself is the target.",
            "Use clean phoneme production and avoid extra vowel sounds.",
            "Move from teacher model to guided practice to independent attempts.",
            "Use multiple equivalent examples rather than repeating one memorized word.",
        ],
        steps=[
            "Teacher demonstrates one example by saying separate phonemes and smoothly blending them.",
            "Learner practices 2-3 supported oral blends.",
            "Reduce support and present several independent CVC blends.",
            "Mix previously successful and novel equivalent items.",
            "If oral blending stabilizes, introduce simple printed words using known grapheme-sound mappings.",
        ],
        practice_constraints=[
            "Do not show print during the initial oral blending check unless print is intentionally part of the task.",
            "Use unfamiliar equivalent items for verification.",
            "Record whether any prompt, repetition, or model was needed.",
        ],
        do_not_do=[
            "Do not call blending difficulty dyslexia.",
            "Do not teach the exact verification items during intervention.",
        ],
        expected_immediate_signal="Independent oral blending improves on new CVC examples.",
        expected_transfer_signal="Improved decoding of unfamiliar simple printed words when grapheme-sound knowledge is secure.",
        falsification_signal="Oral blending remains weak despite acceptable-fidelity explicit practice, or oral blending improves while matched decoding does not.",
        evidence_basis=[
            "Phonemic awareness instruction including blending is an established foundational-reading practice.",
            "ReadRight pilot dosage and item sequence remain unvalidated.",
        ],
    ),
    "INT-SEG-EXPLICIT": InterventionSpec(
        intervention_id="INT-SEG-EXPLICIT",
        hypothesis_id="H-SEG",
        target_skill_id="EN-PHON-SEG",
        title="Explicit phoneme segmentation routine",
        purpose="Strengthen the ability to identify and sequence individual phonemes in spoken words.",
        group_size="1-4 learners",
        duration_minutes=8,
        sessions_per_week=4,
        delivery_principles=[
            "Begin with spoken words and explicit modelling.",
            "Use manipulatives only as temporary scaffolds, not as the final response mode.",
            "Fade support toward independent oral segmentation.",
        ],
        steps=[
            "Teacher models segmenting one simple word into phonemes.",
            "Learner segments supported examples using counters or finger taps if useful.",
            "Remove the scaffold and ask for oral segmentation of equivalent new items.",
            "Mix beginning, middle, and ending phoneme attention across examples.",
            "Connect to spelling only after the oral sequence can be produced reliably.",
        ],
        practice_constraints=[
            "Use words appropriate to the learner's spoken-language variety.",
            "Avoid interpreting speech-production differences as segmentation failure without review.",
        ],
        do_not_do=[
            "Do not infer spelling ability directly from oral segmentation alone.",
            "Do not overtrain the exact assessment items.",
        ],
        expected_immediate_signal="Improved independent segmentation of unpractised simple spoken words.",
        expected_transfer_signal="Improved sound-to-symbol encoding on simple unfamiliar spelling items when grapheme knowledge is available.",
        falsification_signal="Segmentation improves but encoding remains weak, suggesting a different or additional bottleneck.",
        evidence_basis=[
            "Phonemic segmentation is a core phonemic-awareness skill used in early reading and spelling instruction.",
            "ReadRight pilot routines require field validation.",
        ],
    ),
    "INT-DECODE-GUIDED": InterventionSpec(
        intervention_id="INT-DECODE-GUIDED",
        hypothesis_id="H-DECODE",
        target_skill_id="EN-DECODE-NONWORD",
        title="Cumulative decoding routine",
        purpose="Strengthen application of known print-sound correspondences to unfamiliar printed forms.",
        group_size="1-4 learners",
        duration_minutes=10,
        sessions_per_week=4,
        delivery_principles=[
            "Use grapheme-sound patterns the learner has already been taught.",
            "Require attention to every grapheme rather than guessing from context.",
            "Include both real and unfamiliar pronounceable items.",
            "Increase complexity gradually.",
        ],
        steps=[
            "Review the required grapheme-sound correspondences.",
            "Teacher models decoding one unfamiliar item by attending to each grapheme and blending.",
            "Learner decodes a short set of matched items with immediate corrective feedback.",
            "Fade prompting and present equivalent unseen items independently.",
            "Finish with a small mixed set of real and unfamiliar items.",
        ],
        practice_constraints=[
            "Only use item structures supported by taught correspondences.",
            "Do not score memorized real-word recognition as proof of productive decoding.",
            "Reserve verification forms so they remain unseen.",
        ],
        do_not_do=[
            "Do not encourage picture/context guessing as the decoding strategy.",
            "Do not diagnose dyslexia from nonword performance.",
        ],
        expected_immediate_signal="Improved independent decoding accuracy on new matched unfamiliar items.",
        expected_transfer_signal="Improved reading of new real words sharing the taught orthographic patterns.",
        falsification_signal="Grapheme-sound knowledge and oral blending are secure but unfamiliar decoding does not improve after acceptable-fidelity instruction.",
        evidence_basis=[
            "Systematic decoding instruction and practice applying sound-symbol knowledge to words are foundational reading practices.",
            "ReadRight's exact pilot item progression remains unvalidated.",
        ],
    ),
    "INT-AUTO-REPEATED": InterventionSpec(
        intervention_id="INT-AUTO-REPEATED",
        hypothesis_id="H-AUTO",
        target_skill_id="EN-WORD-AUTO",
        title="Accuracy-first word automaticity practice",
        purpose="Increase efficient retrieval of already-decodable words without sacrificing accuracy.",
        group_size="1-4 learners",
        duration_minutes=8,
        sessions_per_week=4,
        delivery_principles=[
            "Accuracy precedes speed.",
            "Use words the learner can decode rather than introducing untaught patterns.",
            "Track errors and self-corrections as well as time.",
        ],
        steps=[
            "Confirm the learner can decode the selected words accurately without timing.",
            "Practice a short mixed word set with immediate correction.",
            "Repeat the set only a small number of times.",
            "Introduce a parallel set with the same patterns.",
            "Compare accuracy and latency without pressuring the learner to race.",
        ],
        practice_constraints=[
            "Do not use speed practice on words that are not yet decodable.",
            "Do not interpret faster but less accurate performance as improvement.",
        ],
        do_not_do=[
            "Do not turn fluency work into a speed contest.",
            "Do not use one timed score as a mastery claim.",
        ],
        expected_immediate_signal="Stable accuracy with reduced latency on familiar but not memorized-by-test items.",
        expected_transfer_signal="More fluent reading of short connected text containing similar word patterns.",
        falsification_signal="Word-level accuracy/latency improves but connected-text fluency remains weak.",
        evidence_basis=[
            "Fluency development requires accurate word recognition and supported repeated practice.",
            "ReadRight pilot timing rules require calibration.",
        ],
    ),
    "INT-ORF-GUIDED": InterventionSpec(
        intervention_id="INT-ORF-GUIDED",
        hypothesis_id="H-ORF",
        target_skill_id="EN-ORF",
        title="Guided connected-text fluency practice",
        purpose="Improve accurate, increasingly smooth reading of connected text after word-level reading is sufficiently secure.",
        group_size="1-4 learners",
        duration_minutes=10,
        sessions_per_week=4,
        delivery_principles=[
            "Preserve accuracy before rate.",
            "Use brief teacher modelling and supported rereading.",
            "Track errors, self-corrections, phrasing, and rate separately.",
        ],
        steps=[
            "Preview only vocabulary needed to understand the passage, without pre-reading every word.",
            "Teacher models a short section with natural phrasing.",
            "Learner reads the passage with correction when needed.",
            "Learner rereads once or twice with reduced support.",
            "Use a new parallel passage to check transfer rather than only the practised passage.",
        ],
        practice_constraints=[
            "Use text aligned to the learner's decoding knowledge.",
            "Never interpret rate without accuracy.",
        ],
        do_not_do=[
            "Do not repeatedly drill one passage until memorized and call that general fluency.",
            "Do not rank children publicly by speed.",
        ],
        expected_immediate_signal="More accurate and smoother reading on the practised passage with reduced support.",
        expected_transfer_signal="Improved accuracy/rate pattern on a parallel unseen passage.",
        falsification_signal="Practised-passage performance improves but parallel-passage reading does not.",
        evidence_basis=[
            "Guided repeated oral reading is a well-established fluency practice when accuracy and feedback are preserved.",
            "ReadRight passage equivalence and dosage require calibration.",
        ],
    ),
    "INT-ORAL-LANG": InterventionSpec(
        intervention_id="INT-ORAL-LANG",
        hypothesis_id="H-ORAL-LANG",
        target_skill_id="EN-ORAL-COMP",
        title="Oral language comprehension support",
        purpose="Strengthen understanding of spoken vocabulary, sentence relationships, and simple inference before attributing comprehension difficulty to reading alone.",
        group_size="1-4 learners",
        duration_minutes=10,
        sessions_per_week=3,
        delivery_principles=[
            "Use spoken language at an accessible level.",
            "Teach vocabulary in meaningful sentence/story contexts.",
            "Ask both literal and simple inferential questions.",
        ],
        steps=[
            "Introduce a few target words in a short oral context.",
            "Check understanding with child-friendly explanations/examples.",
            "Read or tell a brief passage aloud.",
            "Ask literal then inferential comprehension questions.",
            "Ask the learner to retell the central idea in their own words.",
        ],
        practice_constraints=[
            "Interpret performance in the learner's language-of-instruction and exposure context.",
            "Do not confuse limited English exposure with a reading-specific barrier.",
        ],
        do_not_do=[
            "Do not use this routine to diagnose language disorder.",
            "Do not infer reading comprehension from oral comprehension alone.",
        ],
        expected_immediate_signal="Improved understanding of directly taught oral vocabulary and relations.",
        expected_transfer_signal="Better comprehension of a new orally presented passage with similar language demands.",
        falsification_signal="Oral comprehension is secure while reading comprehension remains weak, supporting a reading-specific alternative.",
        evidence_basis=[
            "Oral language and vocabulary are important contributors to reading comprehension.",
            "ReadRight pilot intervention dosage remains unvalidated.",
        ],
    ),
    "INT-COMP-EXPLICIT": InterventionSpec(
        intervention_id="INT-COMP-EXPLICIT",
        hypothesis_id="H-COMP",
        target_skill_id="EN-READ-COMP",
        title="Explicit text comprehension routine",
        purpose="Support understanding of text when decoding and oral-language prerequisites are sufficiently demonstrated.",
        group_size="1-4 learners",
        duration_minutes=10,
        sessions_per_week=3,
        delivery_principles=[
            "Use text the learner can decode with manageable effort.",
            "Model how to locate explicit information and connect clues for simple inferences.",
            "Require answers grounded in the text.",
        ],
        steps=[
            "Confirm key vocabulary needed for the short passage.",
            "Learner reads the passage with minimal necessary support.",
            "Ask one literal question and point back to textual evidence.",
            "Model one simple inference from two clues.",
            "Learner answers a new literal/inferential question on a parallel text.",
        ],
        practice_constraints=[
            "Do not use comprehension failure as the primary interpretation when decoding remains substantially uncertain.",
            "Keep oral-language context visible in interpretation.",
        ],
        do_not_do=[
            "Do not reward guessing unsupported by the text.",
            "Do not collapse decoding and comprehension into one score.",
        ],
        expected_immediate_signal="More accurate text-grounded answers on the taught passage.",
        expected_transfer_signal="Improved literal/inferential comprehension on a new matched passage.",
        falsification_signal="Oral language and decoding are secure but reading comprehension remains unchanged after acceptable-fidelity support.",
        evidence_basis=[
            "Reading comprehension benefits from explicit attention to meaning, vocabulary, and text-based reasoning after word-reading demands are considered.",
            "ReadRight pilot routine requires validation.",
        ],
    ),
    "INT-SPELL-ENCODE": InterventionSpec(
        intervention_id="INT-SPELL-ENCODE",
        hypothesis_id="H-SPELL",
        target_skill_id="EN-SPELL",
        title="Sound-to-symbol spelling routine",
        purpose="Strengthen explicit encoding from phoneme sequence to written graphemes.",
        group_size="1-4 learners",
        duration_minutes=8,
        sessions_per_week=4,
        delivery_principles=[
            "Connect phoneme segmentation directly to grapheme selection.",
            "Use patterns already introduced instructionally.",
            "Separate handwriting difficulty from spelling analysis where necessary.",
        ],
        steps=[
            "Say a simple target word and confirm meaning if it is a real word.",
            "Learner segments the phonemes orally.",
            "Learner maps each phoneme to a grapheme and writes/types the word.",
            "Teacher gives immediate corrective feedback linked to the sound sequence.",
            "Verify with new real and unfamiliar items using the same taught correspondences.",
        ],
        practice_constraints=[
            "Allow an alternate response mode if handwriting/motor output would contaminate spelling evidence.",
            "Do not teach the exact verification items.",
        ],
        do_not_do=[
            "Do not interpret handwriting neatness as orthographic knowledge.",
            "Do not infer dyslexia from spelling errors alone.",
        ],
        expected_immediate_signal="Improved sound-to-symbol encoding on taught-pattern items.",
        expected_transfer_signal="Improved spelling of unseen items using the same taught correspondences.",
        falsification_signal="Oral segmentation and grapheme-sound mapping are secure but encoding does not improve.",
        evidence_basis=[
            "Spelling/encoding instruction benefits from explicit phoneme-grapheme mapping within structured foundational literacy instruction.",
            "ReadRight pilot routine requires calibration.",
        ],
    ),
}


def get_intervention(intervention_id: str) -> InterventionSpec | None:
    return INTERVENTIONS.get(intervention_id)


def interventions_for_hypothesis(hypothesis_id: str) -> list[InterventionSpec]:
    return [item for item in INTERVENTIONS.values() if item.hypothesis_id == hypothesis_id]
